# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/cloudkite-public/docker-images/airflow:3.0.2-202507041820',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/cloudkite-public/docker-images/airflow:3.0.2-202507041820'
      ]
images:
  - 'us-central1-docker.pkg.dev/cloudkite-public/docker-images/airflow:3.0.2-202507041820'
