name: Publish atlantis-aws-image

env:
  IMAGE_NAME: atlantis-aws
  GAR_LOCATION: us-central1
  PROJECT_NAME: cloudkite-public
  PROJECT_ID: 297731695546
  REPOSITORY: docker-images

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [atlantis-aws/**]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/github-actions/providers/github-oidc
          service_account: github-actions@${{ env.PROJECT_NAME }}.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Docker configuration
        run: gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev --quiet
      - name: Build and push image
        working-directory: ${{ env.IMAGE_NAME }}
        run: |
          export DATE=$(date +'%m%d%Y')
          docker build -f Dockerfile \
            -t $GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/$IMAGE_NAME:$DATE .
          docker push -a $GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/$IMAGE_NAME